# https://github.com/rak8s/rak8s/blob/master/roles/cleanup/tasks/main.yml

---
- hosts: kubepi
  remote_user: pi
  become: yes
  gather_facts: no

  tasks:
  - name: "Reset Kubernetes"
    shell: echo $(kubeadm reset -f && echo 'true')

  - name: "Remove docker images"
    shell: echo $(docker rmi --force $(docker images --all -q) && echo 'true')
    become: true

  - name: "apt-get update"
    apt:
      update_cache: yes
      autoclean: yes
      autoremove: yes

  - name: "apt-get purge packages"
    apt:
      name: "{{ packages }}"
      state: absent
      purge: yes
      autoremove: yes
      force: yes
    vars:
      packages:
      - kubelet
      - kubeadm
      - kubectl
      - docker-ce

  - name: "Remove pod logging"
    shell: rm -rf /var/log/pods/*
    become: True

  - name: Reboot
    shell: sleep 2 && shutdown -r now "Ansible Reboot"
    async: 1
    poll: 0
    ignore_errors: True

  - name: Wait for Reboot
    local_action: wait_for
    args:
      host: "{{ inventory_hostname }}"
      port: 22
      delay: 15
      timeout: 120
    become: False