---
- hosts: kubepi
  remote_user: pi
  become: yes
  gather_facts: no
  tasks:
  - name: Install updates via apt
    apt:
      update_cache: yes
      upgrade: full
      autoclean: yes
      autoremove: yes
